server.port: 8080

# ip will be provided via env var
database:
  database: inventory
  schema: inventory
  username: inventory_system
  password: asdasd
  port: 5432

#logging:
#  level:
#    org.springframework: debug

# jwt will be provided via env var
#jwt:
#  public:
#  private:
#  random: true


# s3 credentials via env
# s3 url is straightforward
image:
  bucket: images

# embedding? uh that's sagemaker. VIA sagemaker_model_arn
#embeddingurl: http://172.16.0.191:8080

# model url will be provided via env var
#modelurl: http://172.16.2.136:8080
spring:
  main:
    allow-bean-definition-overriding: true

