server.port: 8080

database:
  database: seda
  schema: inventory
  username: inventory_system
  password: asdasd
  port: 5432
  hostname: localhost

jwt:
  public:
  private:
  random: true

generatorId: 1

image:
  access-key: 05365oJVq3GIHvxP
  secret-key: 0dRJR2OgOsoYhZ6TkhVOZb2mre2O6dzv
  url: https://seda-inventory.kro.kr/s3/
  bucket: images
