server.port: 8080

database:
  database: inventory
  schema: inventory
  username: inventory_system
  password: asdasd
  port: 5432
  hostname: 172.16.3.156

jwt:
  public:
  private:
  random: true

generatorId: 1

image:
  access-key: 5294b88d9d5f4bb78e02b1dcfc182dc7
  secret-key: 8eb082fd2aca458b812f133615187791
  url: https://s4.cloud.seda.club/
  bucket: images


embeddingurl: http://172.16.0.191:8080
modelurl: http://172.16.2.136:8080